# Site Settings
title: Sentient Biotech Private Limited
description: Neurotech solutions for mental and physical health
baseurl: "" # Leave this blank for a root URL
url: "https://sentientbiotech.github.io" # Your site's URL

# Theme settings
remote_theme: pages-themes/cayman-dark@v0.2.0

# To remove "View on GitHub"
plugins:
  - jekyll-optional-view-on-github

# Header customization
header_pages:
  - about.md
  - projects.md
  - contact.md

# Custom CSS
custom_css:
  - assets/css/style.css
