# Site settings
title: Sentient Biotech
description: Pioneering Neurotechnology for holistic well-being
url: "https://sentientbiotech.github.io/"  # Replace with your actual URL

# Theme settings
theme: minima
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Customization
show_downloads: false

# Color scheme
colors:
  primary: "#007bff"  # A tech-friendly blue
  secondary: "#6c757d"
  background: "#f8f9fa"
  text: "#212529"

  # Navigation
header_pages:
  - Product.md
  - What is Brain-Computer Interface [BCI]?.md
  - Equilibrium Psychology [EqP].md
  - Mental Health for All.md

# Social links
github_username: sentientbiotech
linkedin_username: sentient-biotech
twitter_username: sentientbiotech

# Build settings
markdown: kramdown
