# Site settings
title: "Sentient Biotech"
description: "Innovating Brain-Computer Interface & Neurotechnology"
baseurl: "" # Leave this empty unless your site is in a subfolder
url: "https://SentientBiotech.github.io" # Update with your GitHub Pages URL

# Theme settings
theme: jekyll-theme-slate  # A dark theme that will give your site a sleek look
plugins:
  - jekyll-seo-tag  # For better SEO metadata
  - jekyll-optional-view-on-github  # To remove "View on GitHub"

# Optional: Remove the default "View on GitHub" link
exclude:
  - "README.md"

# Navigation menu (based on your sections)
header_pages:
  - Equilibrium Pscychology [EqP].md
  - Mental Health for All.md
  - Product.md
  - What is Brain-Computer Interface [BCI]?.md

# Markdown options
markdown: kramdown
kramdown:
  input: GFM  # GitHub Flavored Markdown

# Build settings
future: true
