title: "Sentient Biotech Private Limited"
description: "Neurotech and BCI Solutions"
theme: jekyll-theme-minimal

# Customization settings for dark theme
markdown: kramdown

# Set dark mode directly in the config
minima:
  skin: dark

# Author settings (Optional)
author:
  name: "Sentient Biotech Team"
  email: "contact@sentientbiotech.com"

# Other settings
permalink: /:path/
